<a href="https://colab.research.google.com/github/Nbbrrsss/Preprocessing-Data/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas Pertemuan 3 Data Mining
Nama   : Nibras Bahy Ardyansyah

Nim    : A11.2021.13515

Matkul : Data Mining (A11.4403)




In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

> Numpy
merupakan library python digunakan untuk komputeasi matriks.

> Matplotlib
merupakan library python untuk presentasi data berupa grafik atau plot.



In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Germany' 25.0 55000.0]
 ['Spain' 30.0 53000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 62000.0]
 ['France' 35.0 58000.0]
 ['Spain' 36.72727272727273 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Germany' 25.0 55000.0]
 ['Spain' 30.0 53000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 62000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 36.72727272727273 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 25.0 55000.0]
 [0.0 0.0 1.0 30.0 53000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [12]:
print(x_train)

[[0.0 1.0 0.0 25.0 55000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 36.72727272727273 52000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 30.0 53000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 62000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 1 1 0 1]


In [15]:
print(y_test)

[0 0 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 1.0 0.0 -1.4238140696240553 -0.6687338550904234]
 [0.0 0.0 1.0 -1.1859109592564916 -1.253875978294544]
 [0.0 0.0 1.0 -0.028836740650613753 -0.9195090507493322]
 [1.0 0.0 0.0 0.8362654788677998 0.7523255869767264]
 [1.0 0.0 0.0 1.3120716996029271 1.3374677101808468]
 [0.0 0.0 1.0 -0.8290562937051461 -0.8359173188630292]
 [1.0 0.0 0.0 0.003604592581326825 0.3343669275452117]
 [0.0 1.0 0.0 1.5499748099704909 1.6718346377260584]
 [1.0 0.0 0.0 -0.23429851778623687 -0.4179586594315146]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 -0.8290562937051461 -0.7523255869767264]
 [0.0 0.0 1.0 0.12255614776510868 -0.16718346377260584]
 [0.0 1.0 0.0 0.3604592581326724 -0.08359173188630292]]
